/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PerguntaController;
import model.Pergunta;

public class PerguntaCadastro extends javax.swing.JFrame {
    PerguntaController controller;
    Pergunta pergunta;

    PerguntaCadastro(Pergunta pergunta) {
        initComponents();
        this.setResizable(false);
        botaoExcluir.setVisible(false);
        controller = new PerguntaController();
        this.pergunta = pergunta;
        if (pergunta != null) {
            preencherFormulario(pergunta);
            botaoExcluir.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoTitulo = new javax.swing.JLabel();
        textoPergunta = new javax.swing.JLabel();
        campoPergunta = new javax.swing.JTextField();
        textoA = new javax.swing.JLabel();
        campoA = new javax.swing.JTextField();
        textoB = new javax.swing.JLabel();
        campoB = new javax.swing.JTextField();
        textoC = new javax.swing.JLabel();
        campoC = new javax.swing.JTextField();
        textoD = new javax.swing.JLabel();
        campoD = new javax.swing.JTextField();
        textoOpcoes = new javax.swing.JLabel();
        textoOpcaoCorreta = new javax.swing.JLabel();
        campoOpcaoCorreta = new javax.swing.JTextField();
        botaoCadastrar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        textoTitulo.setText("Cadastre uma nova pergunta");

        textoPergunta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoPergunta.setText("Informe a pergunta");

        textoA.setText("A)");

        campoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAActionPerformed(evt);
            }
        });

        textoB.setText("B)");

        textoC.setText("C)");

        textoD.setText("D)");

        textoOpcoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoOpcoes.setText("Informe as opções de resposta");

        textoOpcaoCorreta.setText("Informe a opção correta");

        campoOpcaoCorreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoOpcaoCorretaActionPerformed(evt);
            }
        });

        botaoCadastrar.setText("Salvar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoPergunta)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoTitulo)
                            .addComponent(textoOpcoes)
                            .addComponent(textoPergunta))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoB)
                            .addComponent(textoA)
                            .addComponent(textoC)
                            .addComponent(textoD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoOpcaoCorreta, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoOpcaoCorreta)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(campoD)
                            .addComponent(campoC)
                            .addComponent(campoB)
                            .addComponent(campoA))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoTitulo)
                .addGap(18, 18, 18)
                .addComponent(textoPergunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(textoOpcoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoA)
                    .addComponent(campoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoB)
                    .addComponent(campoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoC)
                    .addComponent(campoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoOpcaoCorreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoOpcaoCorreta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrar)
                    .addComponent(botaoCancelar)
                    .addComponent(botaoExcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAActionPerformed

    private void campoOpcaoCorretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoOpcaoCorretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoOpcaoCorretaActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        Pergunta p = capturarPergunta();
        if (this.pergunta == null) {
            controller.salvarPergunta(p);
        }else{
            p.setId(this.pergunta.getId());
            controller.atualizarPergunta(p);
        }
            
        
        mostrarListagem();
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.pergunta = null;
        mostrarListagem();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        controller.excluir(this.pergunta.getId());
        mostrarListagem();
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void mostrarListagem(){
        PerguntaListagem p = new PerguntaListagem();
        p.setTitle("Listagem de Perguntas");
        p.setLocationRelativeTo(null);
        this.setVisible(false);
        p.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JTextField campoA;
    private javax.swing.JTextField campoB;
    private javax.swing.JTextField campoC;
    private javax.swing.JTextField campoD;
    private javax.swing.JTextField campoOpcaoCorreta;
    private javax.swing.JTextField campoPergunta;
    private javax.swing.JLabel textoA;
    private javax.swing.JLabel textoB;
    private javax.swing.JLabel textoC;
    private javax.swing.JLabel textoD;
    private javax.swing.JLabel textoOpcaoCorreta;
    private javax.swing.JLabel textoOpcoes;
    private javax.swing.JLabel textoPergunta;
    private javax.swing.JLabel textoTitulo;
    // End of variables declaration//GEN-END:variables

    private Pergunta capturarPergunta() {
        String pergunta = campoPergunta.getText();
        String opcaoA = campoA.getText();
        String opcaoB = campoB.getText();
        String opcaoC = campoC.getText();
        String opcaoD = campoD.getText();
        String opcaoCorreta = campoOpcaoCorreta.getText();
        
        Pergunta p = new Pergunta(pergunta, opcaoA, opcaoB, opcaoC, opcaoD, opcaoCorreta);
        return p;
    }

    private void preencherFormulario(Pergunta pergunta) {
        campoPergunta.setText(pergunta.getPergunta());
        campoA.setText(pergunta.getA());
        campoB.setText(pergunta.getB());
        campoC.setText(pergunta.getC());
        campoD.setText(pergunta.getD());
        campoOpcaoCorreta.setText(pergunta.getOpcaoCorreta());
    }
}
