/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PerguntaController;
import controller.RespostaController;
import java.util.ArrayList;
import model.Pergunta;

public class RespostaExibicao extends javax.swing.JFrame {

    int pg = 0;
    String OpcaoCorreta = null;
    double Acertos = 0;
    RespostaController controller2;
    PerguntaController controller;

    public RespostaExibicao() {
        initComponents();
        pg = 0;
        controller = new PerguntaController();
        Pergunta(pg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoPerguntaImperativa = new javax.swing.JLabel();
        CampoRespostaA = new javax.swing.JLabel();
        CampoRespostaB = new javax.swing.JLabel();
        CampoRespostaC = new javax.swing.JLabel();
        CampoRespostaD = new javax.swing.JLabel();
        BotaoProximaPergunta = new javax.swing.JButton();
        CampoResposta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CampoPergunta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextoPerguntaImperativa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextoPerguntaImperativa.setText("Responda a pergunta abaixo:");

        CampoRespostaA.setText("jLabel3");

        CampoRespostaB.setText("jLabel4");

        CampoRespostaC.setText("jLabel5");

        CampoRespostaD.setText("jLabel6");

        BotaoProximaPergunta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotaoProximaPergunta.setText("Proxima Pergunta");
        BotaoProximaPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoProximaPerguntaActionPerformed(evt);
            }
        });

        CampoResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoRespostaActionPerformed(evt);
            }
        });

        jLabel1.setText("Informe sua resposta");

        CampoPergunta.setText("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        CampoPergunta.setMaximumSize(new java.awt.Dimension(500, 30));

        jLabel2.setText("A)");

        jLabel3.setText("B)");

        jLabel4.setText("C)");

        jLabel5.setText("D)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CampoResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoProximaPergunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(357, 357, 357))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(TextoPerguntaImperativa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoRespostaA, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(CampoRespostaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CampoRespostaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CampoRespostaD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CampoPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(TextoPerguntaImperativa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoRespostaA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoRespostaB)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoRespostaC)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoRespostaD)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoResposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(BotaoProximaPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoRespostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoRespostaActionPerformed

    private void BotaoProximaPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoProximaPerguntaActionPerformed
        String resposta = CampoResposta.getText();
        if (pg == 9) {
            RespostaResultado rr = new RespostaResultado();
            rr.setTitle("Resultado");
            rr.setLocationRelativeTo(null);
            this.setVisible(false);
            rr.setVisible(true);
            double Erro = 10 - Acertos;
            double Acertos1 = (Acertos / 10) * 100;
            String Acerto = Double.toString(Acertos1);
            rr.Porcentagem.setText(Acerto + "%");
            rr.acertoserro.setText("Você acertou " + Acertos + " e errou " + Erro);

        } else if ("a".equals(CampoResposta.getText()) || "b".equals(CampoResposta.getText()) || "c".equals(CampoResposta.getText()) || "d".equals(CampoResposta.getText())) {
            pg = pg + 1;
            Pergunta(pg);
            if (OpcaoCorreta.equals(resposta)) {
                Acertos = Acertos + 1;
            }
        }


    }//GEN-LAST:event_BotaoProximaPerguntaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespostaExibicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespostaExibicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespostaExibicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespostaExibicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespostaExibicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoProximaPergunta;
    private javax.swing.JLabel CampoPergunta;
    private javax.swing.JTextField CampoResposta;
    private javax.swing.JLabel CampoRespostaA;
    private javax.swing.JLabel CampoRespostaB;
    private javax.swing.JLabel CampoRespostaC;
    private javax.swing.JLabel CampoRespostaD;
    private javax.swing.JLabel TextoPerguntaImperativa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
        public Pergunta Pergunta(int pg) {
        ArrayList<Pergunta> listaPerguntas = controller.RandomizarPergunta();
        Pergunta p = listaPerguntas.get(pg);
        CampoPergunta.setText(p.getPergunta());
        CampoRespostaA.setText(p.getA());
        CampoRespostaB.setText(p.getB());
        CampoRespostaC.setText(p.getC());
        CampoRespostaD.setText(p.getD());
        OpcaoCorreta = p.getOpcaoCorreta();
        return p;
    }

}
